### ISSUE TITLE
Exception on exit...

### ISSUE THREAD

**Issue by smblott-github** [balloob/pychromecast#115]
On exit, I'm usually (not always) seeing...

    Exception in thread Thread-1 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
      File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 349, in run
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'SSLError'

Any ideas?  What is the approved method of disconnecting before exit?

**Comment by balloob** [comment]
Are you using 0.7.4 that got released 2 hours ago? It has a fix for errors on closing

**Comment by smblott-github** [comment]
Yes, I'm using 0.7.4.  (Searched the issues, saw that one and upgraded to check before posting.)

    $ pip show -f pychromecast
    ---
    Metadata-Version: 2.0
    Name: PyChromecast
    Version: 0.7.4
    Summary: Python module to talk to Google Chromecast.
    ...

**Comment by smblott-github** [comment]
Curious...

I added some hackery to try to shut up the error messages:

```python
if cast:
   try:
      sys.stderr = open("/dev/null", "w")
      cast.disconnect(None, False)
   except:
      print "(error on disconnect)"
      pass
```

This is right at the end of my script.

And I still see this message (on stderr!):

    Exception in thread Thread-5 (most likely raised during interpreter shutdown):

So the problem is happening *very late* in the shutdown sequence.
