### ISSUE TITLE
youtube play_video not found error?

### ISSUE THREAD

**Issue by strunker** [balloob/pychromecast#183]
Hello.

So I have been using the media controller functionality for a while. I can stream mp3s from my own server to my chromecast devices without issue.

More recently I have wanted to utilize google search api, and get the youtube controller function to work.

Below is a snippet of some code. 

In short I define a chromecast object, CC2. Then register the youtube handler (yt) to it. This is the same, for the most part, how this is done in the example code. the video id seen below is valid. I get a not_found error, not really sure what to make of that.

Thanks. 

import pychromecast #used for chromecast func
import pychromecast.controllers.youtube as youtube

```
#define constants for Chromecast 
CC2 = pychromecast.Chromecast("10.1.1.12")
Kitchen = CC2.media_controller
yt = youtube.YouTubeController()
print dir(yt)
CC2.register_handler(yt)

yt.play_video("j04JKdcXjkU")

```

    ```
yt.play_video("j04JKdcXjkU")
  File "C:\Python27\lib\site-packages\pychromecast\controllers\youtube.py", line 38, in play_video
    self.launch()
  File "C:\Python27\lib\site-packages\pychromecast\controllers\__init__.py", line 44, in launch
    self.supporting_app_id)
  File "C:\Python27\lib\site-packages\pychromecast\socket_client.py", line 816, in launch_app
    app_id, launch_error.reason))
pychromecast.error.LaunchError: Failed to launch app: 233637DE, Reason: NOT_FOUND
```

**Comment by strunker** [comment]
So kind of sorted this. 

It looks like if you try to send a youtube video to an audio dongle it generates this error, when sending to a normal chromecast devices it doesnt error.

still doesnt seem to work however, I see the red youtube screen but no video actually starts to play.

I was trying to send just the audio track over to the chromecast dongle. Similar to what I am doing with the media controller. 

thanks.

**Comment by PraveenkumarDonga** [comment]
hi!
Facing the same Error. I am just getting the youtube name with the red background.
is there any solution for this issue.
Looking forward for your help?

Thanks!

**Comment by theychx** [comment]
The YouTube-controller currently in pychromecast is broken, for reference please see: https://github.com/balloob/pychromecast/issues/62

Someone made a working prototype controller that interfaces with YouTube Queue. Get it here: https://github.com/ur1katz/pychromecast/blob/master/pychromecast/controllers/youtube.py

**Comment by strunker** [comment]
I am pretty sure YouTube broke this functionality a while back I was reading other threads which stated it.

Are you trying to mostly play the audio? Do you care about the video?

-----Original Message-----

**Comment by PraveenkumarDonga** [comment]
Hi!
from my  side, I am trying for both audio and video.

**Comment by theychx** [comment]
The YouTube cc-app is not available for audio devices.

**Comment by strunker** [comment]
Yes. I kind of "fixed" this by doing the following for chromecast audio. 

build a youtube search algorithm. You would place your song name inside the query string var below. Once song is located we use youtube_dl library to extract the audio link. We dont download it... Simply extract the link, and then send that link over to the chromecast

import urllib #for youtube parsing
import youtube_dl #use for youtube download
import re #for youtube parsing

def youtubeSearch(SongSearchL):
    try:
        returnlist = []
        f= {}
        f["search_query"] = SongSearchL
        query_string = urllib.urlencode(f)
        final_string = "https://www.youtube.com/results?" + query_string
        html_content = urllib.urlopen(final_string)
        search_results = re.findall(r'href=\"\/watch\?v=(.{11})', html_content.read().decode("utf8"))
        urlfunc = ("http://www.youtube.com/watch?v=" + search_results[0])
        opts = {'format':'bestaudio/best'} #set weird options
        ydl = youtube_dl.YoutubeDL(opts) #make ydl object
        with ydl: 
            result = ydl.extract_info(urlfunc,download=False) # We just want to extract the info
        url = result.get('url')
        trackt = result.get('title')
        returnlist.append(url)
        returnlist.append(trackt)
        return returnlist
    except:
        return "BIG ERROR"



Below is the function call. The function returns the audio link, from there we simply pass to normal media controller and it will start to play the song from youtube. 

                #look on youtube
                info = youtubeSearch(Song)
                if info != "BIG ERROR":
                    url = info[0]
                    trackt = info[1]
                    CC2.set_volume(volume)
                    Kitchen.play_media(url,'audio/mp3')
                    saying = "Playing song in kitchen, " + trackt
                    LastSong = url
                    LastTrack = trackt
                    return statement(saying)
                else:
                    saying = "Could not find song, " + Song
                    return question(saying).reprompt("I did not understand you, what did you want to do?")

**Comment by StarNab** [comment]
https://github.com/balloob/pychromecast/issues/183#issuecomment-325307311
Hello,

I get this error when importing the controller provided ;

```
>>> import pychromecast.controllers.youtube2 as youtube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pychromecast/controllers/youtube2.py", line 27
    REQUEST_PARAMS_SET_PLAYLIST = {**BASE_REQUEST_PARAMS, **SET_PLAYLIST_METHOD}
                                    ^
SyntaxError: invalid syntax

```

Can someone help ?

**Comment by theychx** [comment]
@StarNab 
ur1katz' youtube controlller uses syntax that was introduced in python3.5, so it won't work if you are using any older python interpreter. I've made a few modifications to the controller, so it will work with any python version (from 2.7 and onwards). [Get it here.](https://github.com/skorokithakis/catt/blob/master/catt/youtube.py)

**Comment by StarNab** [comment]
@theychx thanks man, I appreciate. I'll give a try. Will this work by any chance with Youtube live streams ? (I'm also looking for a solution for Twitch streams)

**Comment by StarNab** [comment]
Ok the youtube videos works fine ! Livestreams doesn't seem to be compatible

**Comment by theychx** [comment]
Live streams are working fine for me (such as https://www.youtube.com/watch?v=XOacA3RYrXk).
I'm not sure I understand why it would not work, since you are attempting playback with the official YouTube cc-app. Do have an example url of one of those streams?

**Comment by unknownguy2002** [comment]
For YouTube, I just used pafy to get the url of the video(hosting) and play it as mp4.... If I had seen this I would have known it was fixed...😯

**Comment by unknownguy2002** [comment]
I mean someone else found a fix
