### ISSUE TITLE
Unable to use pychromecast with uwsgi

### ISSUE THREAD

**Issue by bardoup** [balloob/pychromecast#193]
Hello,

I'm trying to make a webservice which receives a phrase and sends it to a chromecast.
When I lanch my webservice with the python interpreter, it works, but when I use uWSGI it doesn't work, throwing the following error : 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 513, in _read_bytes_from_socket
    chunk = self.socket.recv(min(msglen - bytes_recd, 2048))
  File "/usr/lib/python3.5/ssl.py", line 922, in recv
    return self.read(buflen)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 585, in read
    v = self._sslobj.read(len)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2090)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 339, in run
    if self.run_once() == 1:
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 365, in run_once
    message = self._read_message()
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 531, in _read_message
    payload_info = self._read_bytes_from_socket(4)
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 523, in _read_bytes_from_socket
    if _is_ssl_timeout(exc):
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 112, in _is_ssl_timeout
    return exc.message in ("The handshake operation timed out",
AttributeError: 'ssl.SSLError' object has no attribute 'message'
```
What am I doing wrong ?

**Comment by balloob** [comment]
This is not an issue with PyChromecast. uwsgi must be changing something.
