### ISSUE TITLE
 badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by vajonam** [balloob/pychromecast#206]
When using this with python 2.7 I am seeing the following issue. 

`Exception in thread zeroconf-ServiceBrowser__googlecast._tcp.local.:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1334, in run
    handler(self.zc)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1282, in <lambda>
    state_change=state_change,
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1197, in fire
    h(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1255, in on_change
    listener.add_service(*args)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/discovery.py", line 63, in add_service
    uuid = UUID(uuid)
  File "/usr/lib/python2.7/uuid.py", line 136, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
`

when I do a pychromecast.get_chromecasts()

**Comment by OttoWinter** [comment]
What sort of device are you using? Simple fix might be something like in #159.

**Comment by balloob** [comment]
Closing this as we're going to drop Python 2 support (#211)

**Comment by gnumdk** [comment]
For strange reason, this code https://github.com/balloob/pychromecast/pull/159/commits/567d993d028a9a030a489143185e96b97a639a3d is not in 2.2.0... Apply this code fix the issue.
