### ISSUE TITLE
pychromecast sometimes blocks infinite when connecting

### ISSUE THREAD

**Issue by quthla** [balloob/pychromecast#235]
After the device has been idle a few hours, pychromecast does not return from constructor on first try so it's just stuck and I can't even handle it.
On second try it works then as it should.

```
May 17 17:44:53 hass appdaemon[468]: 2018-05-17 17:44:53.667977 INFO radio: connecting to chromecast
May 17 17:44:53 hass appdaemon[468]: INFO:pychromecast:Querying device status
May 17 17:46:11 hass appdaemon[468]: 2018-05-17 17:46:11.253694 INFO radio: connecting to chromecast
May 17 17:46:11 hass appdaemon[468]: Exception in thread Thread-13:
May 17 17:46:11 hass appdaemon[468]: Traceback (most recent call last):
May 17 17:46:11 hass appdaemon[468]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
May 17 17:46:11 hass appdaemon[468]:     self.run()
May 17 17:46:11 hass appdaemon[468]:   File "/usr/lib/python3.6/threading.py", line 864, in run
May 17 17:46:11 hass appdaemon[468]:     self._target(*self._args, **self._kwargs)
May 17 17:46:11 hass appdaemon[468]:   File "/root/.homeassistant/appdaemon/apps/radio.py", line 40, in _play_media
May 17 17:46:11 hass appdaemon[468]:     cast = pychromecast.Chromecast('Chromecast-Audio', timeout=5, tries=2)
May 17 17:46:11 hass appdaemon[468]:   File "/srv/homeassistant/lib/python3.6/site-packages/pychromecast/__init__.py", line 161, in __init__
May 17 17:46:11 hass appdaemon[468]:     "Could not connect to {}:{}".format(self.host, self.port))
May 17 17:46:11 hass appdaemon[468]: pychromecast.error.ChromecastConnectionError: Could not connect to Chromecast-Audio:8009
May 17 17:46:11 hass appdaemon[468]: INFO:pychromecast:Querying device status
May 17 17:46:11 hass appdaemon[468]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): chromecast-audio
May 17 17:46:11 hass appdaemon[468]: DEBUG:urllib3.connectionpool:http://chromecast-audio:8008 "GET /setup/eureka_info?options=detail HTTP/1.1" 200 1477
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.controllers:Receiver:Updating status
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.socket_client:Sending: Message urn:x-cast:com.google.cast.tp.connection from sender-0 to receiver-0: {'type': 'CONNECT', 'origin': {}, 'userAgent': 'PyChromecast', 'senderInfo': {'sdkType': 2, 'version': '15.605.1.3', 'browserVersion': '44.0.2403.30', 'platform': 4, 'systemVersion': 'Macintosh; Intel Mac OS X10_10_3', 'connectionType': 1}}
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.socket_client:Sending: Message urn:x-cast:com.google.cast.receiver from sender-0 to receiver-0: {'type': 'GET_STATUS', 'requestId': 1}
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.socket_client:Connected!
May 17 17:46:11 hass appdaemon[468]: 2018-05-17 17:46:11.316141 INFO radio: waiting for chromecast
May 17 17:46:11 hass appdaemon[468]: DEBUG:root:Thread started...
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.socket_client:Received: Message urn:x-cast:com.google.cast.receiver from receiver-0 to sender-0: {'requestId': 1, 'status': {'userEq': {'high_shelf': {'frequency': 4500.0, 'gain_db': 0.0, 'quality': 0.707}, 'low_shelf': {'frequency': 150.0, 'gain_db': 0.0, 'quality': 0.707}, 'max_peaking_eqs': 0, 'peaking_eqs': []}, 'volume': {'controlType': 'master', 'level': 0.4300000071525574, 'muted': False, 'stepInterval': 0.019999999552965164}}, 'type': 'RECEIVER_STATUS'}
May 17 17:46:11 hass appdaemon[468]: DEBUG:pychromecast.controllers:Received status: CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.4300000071525574, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')

```

```
        import logging
        logging.basicConfig(level=logging.DEBUG)
        self.log('connecting to chromecast')
        cast = pychromecast.Chromecast('Chromecast-Audio', timeout=5, tries=2)
        self.log('waiting for chromecast')
        cast.wait(timeout=5)
```

**Comment by emontnemery** [comment]
Closing since the connection logic is completely changed in release 3.0.0.
