### ISSUE TITLE
AttributeError: 'NodeListClass' object has no attribute 'get'

### ISSUE THREAD

**Issue by simonszu** [balloob/pychromecast#242]
I have this error when using pychromecast with Home Assistant. Not sure where to open the issue. 
However, this is my config:

```
$ cat configuration.yaml
<...>
# Chromecast
cast: !include cast.yaml
```
and
```
$ cat cast.yaml
media_player:
- host: 192.168.10.9
```
this results in this error showing up on the HA status page:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/cast.py", line 205, in async_setup_entry
    async_add_devices, None)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/cast.py", line 214, in _async_setup_platform
    pychromecast.IGNORE_CEC += config.get(CONF_IGNORE_CEC, [])
AttributeError: 'NodeListClass' object has no attribute 'get'
```
I'm running HA with HassIO on a Raspi 3.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant/pull/15143
