### ISSUE TITLE
pychromecast.get_chromecasts() failing and not connecting

### ISSUE THREAD

**Issue by vajonam** [balloob/pychromecast#246]
hi there,

i am not sure when this broke, but this used to work, not sure which update or change broke this. 

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
>>> chromecasts = pychromecast.get_chromecasts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 75, in get_chromecasts
    blocking=blocking))
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 42, in _get_chromecast_from_host
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 169, in __init__
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 208, in __init__
    self.initialize_connection()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 244, in initialize_connection
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
>>> chromecasts = pychromecast.get_chromecasts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 75, in get_chromecasts
    blocking=blocking))
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 42, in _get_chromecast_from_host
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 169, in __init__
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 208, in __init__
    self.initialize_connection()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 244, in initialize_connection
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out

```

**Comment by vajonam** [comment]
duplicate, think I clicked the create button early.
