### ISSUE TITLE
pychromecast.get_chromecasts() failing and not connecting

### ISSUE THREAD

**Issue by vajonam** [balloob/pychromecast#247]
hi there,

i am not sure when this broke, but this used to work, not sure which update or change broke this. 

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
>>> chromecasts = pychromecast.get_chromecasts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 75, in get_chromecasts
    blocking=blocking))
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 42, in _get_chromecast_from_host
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 169, in __init__
    blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 208, in __init__
    self.initialize_connection()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 244, in initialize_connection
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```

Not sure what I am missing or changes. this not being done from inside a docker container but I have tried this on machines without docker installed at all.

**Comment by dtmulc** [comment]
Getting a similar problem. Did you have any luck getting this to work?
`Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
>>> cc = pychromecast.get_chromecasts()
Failed to connect, retrying in 5.0s
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\socket_client.py", line 244, in initialize_connection
    self.socket.connect((self.host, self.port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\__init__.py", line 75, in get_chromecasts
    blocking=blocking))
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\__init__.py", line 42, in _get_chromecast_from_host
    blocking=blocking)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\__init__.py", line 169, in __init__
    blocking=blocking)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\socket_client.py", line 208, in __init__
    self.initialize_connection()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\pychromecast\socket_client.py", line 244, in initialize_connection
    self.socket.connect((self.host, self.port))
KeyboardInterrupt
`

**Comment by jcoutu-va** [comment]
I'm also seeing this on my network where we have a Jamboard.  get_chromcasts() hangs and fails, but discover_chromecasts() works.
