### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by glsf91** [balloob/pychromecast#251]
I have installed pychromecast.
But when doing en import I get an error:
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/.local/lib/python3.5/site-packages/pychromecast/__init__.py", line 12, in <module>
    from .discovery import discover_chromecasts, start_discovery, stop_discovery
  File "/home/john/.local/lib/python3.5/site-packages/pychromecast/discovery.py", line 5, in <module>
    import zeroconf
  File "/home/john/.local/lib/python3.5/site-packages/zeroconf.py", line 320, in <module>
    OptionalExcInfo = Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

Running on Ubuntu.

Can anybody help?

**Comment by vijrohit** [comment]
Try installing as follows:

python3 -m pip install PyChromecast --user

**Comment by glsf91** [comment]
That works. Thanks
