### ISSUE TITLE
win10 1809 - p3.7.2(64bit) pychromecast.error.NotConnected

### ISSUE THREAD

**Issue by strunker** [balloob/pychromecast#274]
Following the examples on the landing page I keep receiving the below. I have tried different machines, different chromecast, it errors at the same place each time. I have python 2.7 running on a different laptop and do not have this issue. I have firewall and windefender turned off. 

Anyone else experience this issue? 

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    mc.play_media('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video/mp4')
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\controllers\media.py", line 480, in play_media
    callback_function=app_launched_callback)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 925, in launch_app
    self.update_status(lambda response:
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 916, in update_status
    callback_function=callback_function_param)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\controllers\__init__.py", line 84, in send_message
    self.namespace, data, inc_session_id, callback_function)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 721, in send_platform_message
    inc_session_id, callback_function_param)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 668, in send_message
    self._ensure_channel_connected(destination_id)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 758, in _ensure_channel_connected
    no_add_request_id=True)
  File "C:\Program Files\Python37\lib\site-packages\pychromecast\socket_client.py", line 715, in send_message
    str(self.port) + " is connecting...")
pychromecast.error.NotConnected: Chromecast 10.1.1.15:8009 is connecting...
>>>

**Comment by strunker** [comment]
This doesn't happen on 32bit version I have uninstalled 64bit 3.7.2 for now due to the above.

**Comment by strunker** [comment]
Whatever is causing this started in pychromecast 3.0 kind of surprised no one else has posted? Having this problem on 3 separate machines on varying versions of Python. Only common factor is 3.0 pychromecast once I backrev im good. 

I have reverted back to 2.4 for the time being which was the last stable release I was using.

**Comment by twosky2000** [comment]
Just stumble over this. don't forget the cast.wait(). There's an example the readme.
