### ISSUE TITLE
Fails to import - AttributeError: module 'google.protobuf.symbol_database' has no attribute 'Default'

### ISSUE THREAD

**Issue by hastarin** [balloob/pychromecast#302]
I recently upgraded my Home Assistant installation and the cast feature is currently broken.

I'm running it in a Python 3.7.3 venv on Raspbian (buster) and get the following error.

```
(homeassistant) homeassistant@HastPi3:~/.homeassistant $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/homeassistant/lib/python3.7/site-packages/pychromecast/__init__.py", line 11, in <module>
    from . import socket_client
  File "/srv/homeassistant/lib/python3.7/site-packages/pychromecast/socket_client.py", line 23, in <module>
    from . import cast_channel_pb2
  File "/srv/homeassistant/lib/python3.7/site-packages/pychromecast/cast_channel_pb2.py", line 14, in <module>
    _sym_db = _symbol_database.Default()
AttributeError: module 'google.protobuf.symbol_database' has no attribute 'Default'

```

**Comment by hastarin** [comment]
Just a note that I downgraded the protobuf library to 3.8.0 and got things working so I guess it's a compatibility issue.

**Comment by opendll** [comment]
You are mention such amazing information. 
So I joined this group for taking and reading more and more knowledge. 
greeting [how to open dll file](https://opendllfiles.com/)
