### ISSUE TITLE
Error when getting active chromecast

### ISSUE THREAD

**Issue by ecerrillo** [balloob/pychromecast#37]
Hi! I'm getting this error every time I try to get the active chromecasts. I worked perfectly in previous versions. Any help?

Python 2.7.8 (default, Oct 19 2014, 16:02:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import time
>>> import pychromecast
>>> pychromecast.get_chromecasts_as_dict().keys()
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/zeroconf.py", line 1020, in run
    event(self.zc)
  File "/usr/local/lib/python2.7/site-packages/zeroconf.py", line 985, in <lambda>
    self.type, record.alias)
  File "pychromecast/discovery.py", line 26, in add_service
    self.services[name] = (service.server, service.port)
AttributeError: 'NoneType' object has no attribute 'server'

[]
>>> cast=pchr.get_chromecast()
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/zeroconf.py", line 1020, in run
    event(self.zc)
  File "/usr/local/lib/python2.7/site-packages/zeroconf.py", line 985, in <lambda>
    self.type, record.alias)
  File "pychromecast/discovery.py", line 26, in add_service
    self.services[name] = (service.server, service.port)
AttributeError: 'NoneType' object has no attribute 'server'

**Comment by balloob** [comment]
It's related to the new mDNS discovery that I introduced last weekend. I'll have a look at it tonight.

It's weird that the service is not known. Do you by any chance have any other Cast capable devices in your network like an Android TV?

**Comment by ecerrillo** [comment]
Thanks for the quick reply! No, I haven't any other device.

**Comment by balloob** [comment]
I added better error handling if we cannot find the service in 9caff9c56bc8ebdc8a2185db9025a7faba43b802. The error should not show up and the Chromecast should be found, can you confirm this for me?

**Comment by ecerrillo** [comment]
Thank you. It worked perfectly now.
