### ISSUE TITLE
ImportError: No module named 'google'

### ISSUE THREAD

**Issue by KeizerDev** [balloob/pychromecast#48]
When I run the example.py file with `python3.4 example.py` I got a strange error:
```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    import pychromecast
  File "/home/robert-jan/Documents/pychromecast/pychromecast/__init__.py", line 11, in <module>
    from . import socket_client
  File "/home/robert-jan/Documents/pychromecast/pychromecast/socket_client.py", line 20, in <module>
    from . import cast_channel_pb2
  File "/home/robert-jan/Documents/pychromecast/pychromecast/cast_channel_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named 'google'
```
How can I make this work correctly?

Keep up the good work!

**Comment by balloob** [comment]
Looks like you didn't install the dependencies for python 3. Try running `python3.4 -m pip install -r requirements.txt`
